<?php

function angular_contact_menu() {
  //$items = array();
  $items['contact_us'] = array(
    'title' => t('Contacts masih dalam tahap percobaan'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('angular_contact_my_form'),
    'access arguments' => array('access content'),
    'description' => t('My form'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
function angular_contact_form() {
  return drupal_get_form('my_module_my_form');
}
function angular_contact_my_form($form_state) {
  drupal_add_library('angularjs', 'angularjs');

  $options = node_type_get_names();

  $form['node_type'] = array(
    '#type' => 'ng_select',
    '#title' => t('Content type'),
    '#options' => $options,
    '#description' => t('Filter by content-type.'),
    '#default_value' => key($options),
    // Define the ng-model and controller.
    '#ng_model' => 'nodeType',
    '#ng_controller' => 'ListCtrl',
    // Add ng-change.
    '#attributes' => array(
      'ng-change' => 'filterNodeType()',
    ),
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#attributes' => array(
      'ng-model' => 'query.title',
      'placeholder' => t('Filter by title'),
      // HTML5 attribute to Prevent from autocomplete to hide our table.
      'autocomplete' => 'off',
    ),
    '#ng_controller' => 'ListCtrl',
  );

  $header = array(
    t('Title'),
    t('Author'),
  );

  $row = array(
    '{{node.title}}',
    '{{node.author.id}}',
  );

  $form['table'] = array(
    '#theme' => 'ng_table',
    '#header' => $header,
    '#row' => $row,
    // Optionally filter query.
    '#ng_repeat' => 'node in nodes.list | filter: query',
  );
  return $form;
}


/*
function angular_contact_nodes_list_form_builder($form, &$form_state) {
  $options = node_type_get_names();

  $form['node_type'] = array(
    '#type' => 'ng_select',
    '#title' => t('Content type'),
    '#options' => $options,
    '#description' => t('Filter by content-type.'),
    '#default_value' => key($options),
    // Define the ng-model and controller.
    '#ng_model' => 'nodeType',
    '#ng_controller' => 'ListCtrl',
    // Add ng-change.
    '#attributes' => array(
      'ng-change' => 'filterNodeType()',
    ),
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#attributes' => array(
      'ng-model' => 'query.title',
      'placeholder' => t('Filter by title'),
      // HTML5 attribute to Prevent from autocomplete to hide our table.
      'autocomplete' => 'off',
    ),
    '#ng_controller' => 'ListCtrl',
  );

  $header = array(
    t('Title'),
    t('Author'),
  );

  $row = array(
    '{{node.title}}',
    '{{node.author.id}}',
  );

  $form['table'] = array(
    '#theme' => 'ng_table',
    '#header' => $header,
    '#row' => $row,
    // Optionally filter query.
    '#ng_repeat' => 'node in nodes.list | filter: query',
  );

  return $form;
}
*/
?>

<?php
	/*
	function angular_contact_menu() {
	  $items ['contact_us'] = array(
	  'title' => 'AngularJS Contacts',
	  'page callback' =>  'all_angular_contact_page',
	  'access arguments' => array('access content'),
	  );
	  $items ['result'] = array(
	  'title' => 'AngularJS Contacts Result',
	  'page callback' =>  'result_page',
	  'access arguments' => array('access content'),
	  );
	  return $items;
	};
	
	function angular_contact_theme() {
		return array(
			'all_angular_contact' => array(
			'template' => 'all-angular_contact',
			),
		);
	}

	function result_theme() {
		return array(
			'result' => array(
			'template' => 'test',
			)
		);
	}	

	function all_angular_contact_page() {
		  // Set the path
		  $path = drupal_get_path('module', 'angular_contact');

		  // Load angular
		  drupal_add_library('angularjs', 'angularjs');

		  // Load the app
		  drupal_add_js($path . '/js/controller.js');

		  //drupal_add_css($path . '/css/bootstrap.css');

		  // Return the HTML template
		  return theme('all_angular_contact');
	}

	function result_page() {
		  // Set the path
		  $path = drupal_get_path('module', 'angular_contact');

		  // Load angular
		  drupal_add_library('angularjs', 'angularjs');

		  // Load the app
		  drupal_add_js($path . '/js/controller.js');

		  //drupal_add_css($path . '/css/bootstrap.css');

		  // Return the HTML template
		  return theme('result');
	}
	*/
?>